accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
  displayName: Alfred
  pronunciation: Alfred
  sampleInvocations:
  - Talk to Alfred
  voice: male_2
projectId: fyp-actionsconsole
usesInteractiveCanvas: true
