accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
  displayName: Final Year Project
  pronunciation: Final Year Project
  sampleInvocations:
  - Talk to Alfred
  voice: male_1
projectId: fyp-actionsconsole
usesInteractiveCanvas: true
